-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE public.vacina
(
    codigo serial NOT NULL,
    nome text,
    descricao text,
    PRIMARY KEY (codigo)
);

CREATE TABLE public.pessoa
(
    codigo serial NOT NULL,
    nome text,
    cpf text,
    data_nascimento date,
    profissao text,
    PRIMARY KEY (codigo)
);

CREATE TABLE public.lote
(
    codigo serial NOT NULL,
    validade date,
    nro_doses_do_lote integer,
    nro_doses_atual integer,
    codigo_vacina integer,
    PRIMARY KEY (codigo)
);

CREATE TABLE public.aplicacao
(
    codigo serial NOT NULL,
    data date,
    codigo_pessoa integer,
    codigo_lote integer,
    PRIMARY KEY (codigo)
);


ALTER TABLE public.lote
    ADD FOREIGN KEY (codigo_vacina)
    REFERENCES public.vacina (codigo)
    NOT VALID;


ALTER TABLE public.aplicacao
    ADD FOREIGN KEY (codigo_pessoa)
    REFERENCES public.pessoa (codigo)
    NOT VALID;


ALTER TABLE public.aplicacao
    ADD FOREIGN KEY (codigo_lote)
    REFERENCES public.lote (codigo)
    NOT VALID;

END;
